import type { Metadata } from "next";
import { Salsa } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const salsa = Salsa({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${salsa.className} antialiased`}>
        <SessionProvider> {children}</SessionProvider>
      </body>
    </html>
  );
}
